name: Deploy the bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy package.json and package-lock.json
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "package*.json"
          target: "${{ secrets.DEPLOY_PATH }}/"

      - name: Copy built files
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./dist/*"
          target: "${{ secrets.DEPLOY_PATH }}/dist/"
          strip_components: 1

      - name: Create .env file on server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Deploy path: ${{ secrets.DEPLOY_PATH }}"
            if [ ! -d "${{ secrets.DEPLOY_PATH }}" ]; then
              echo "ERROR: Directory ${{ secrets.DEPLOY_PATH }} does not exist"
              exit 1
            fi

            cd ${{ secrets.DEPLOY_PATH }}
            echo "Creating .env file in $(pwd)..."
            echo "WIKI_BOT_USERNAME=${{ secrets.WIKI_BOT_USERNAME }}" > .env
            echo "WIKI_BOT_PASSWORD=${{ secrets.WIKI_BOT_PASSWORD }}" >> .env
            echo ".env file created with content:"
            cat .env
            echo "Listing directory:"
            ls -la

      - name: Verify .env existence
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ -f "${{ secrets.DEPLOY_PATH }}/.env" ]; then
              echo ".env exists at ${{ secrets.DEPLOY_PATH }}"
            else
              echo "ERROR: .env file was not found!"
              exit 1
            fi

      - name: Install dependencies on server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            npm ci --production

      - name: Restart ALTERSHAPER
        run: |
          curl -X POST -u "${{ secrets.API_KEY }}:" ${{ secrets.API_URL }}
